### PR TITLE
Upgrade documentations rspec syntax

### PR DESCRIPTION
**Pull request by etagwerker**
This PR is intended to update the Rspec notation.

### CODE REVIEW

**Comment by mauro-oto** [comment]
@etagwerker looks good! Would you mind updating the build status link & image from (https://secure.travis-ci.org/bmabey/email-spec.png)](http://travis-ci.org/bmabey/email-spec) to (https://secure.travis-ci.org/email-spec/email-spec.png)](http://travis-ci.org/email-spec/email-spec)?

Thanks!

**Comment by etagwerker** [comment]
@mauro-oto sure, done!

**Comment by mauro-oto** [comment]
:+1:

**Comment by mauro-oto** [comment]
Thanks!

**Pull request merged**
